---
- name: Configure cluster
  ansible.builtin.shell:
    cmd: "{{ bin_dir }}/kubectl config set-cluster kubernetes-the-hard-way \
    --certificate-authority=ca.pem \
    --embed-certs=true \
    --server=https://{{ item.item.server_address }}:6443 \
    --kubeconfig={{ item.item.name }}.kubeconfig"
    chdir: "{{ cert_dir }}"
- name: Configure credentials
  ansible.builtin.shell:
    cmd: "{{ bin_dir }}/kubectl config set-credentials system:{{ item.item.name }} \
    --client-certificate={{ item.item.name }}.pem \
    --client-key={{ item.item.name }}-key.pem \
    --embed-certs=true \
    --kubeconfig={{ item.item.name }}.kubeconfig"
    chdir: "{{ cert_dir }}"
- name: Configure set context
  ansible.builtin.shell:
    cmd: "{{ bin_dir }}/kubectl config set-context default \
    --cluster=kubernetes-the-hard-way \
    --user=system:{{ item.item.name }} \
    --kubeconfig={{ item.item.name }}.kubeconfig"
    chdir: "{{ cert_dir }}"
- name: Configure use context
  ansible.builtin.shell:
    cmd: "{{ bin_dir }}/kubectl config use-context default --kubeconfig={{ item.item.name }}.kubeconfig"
    chdir: "{{ cert_dir }}"