- name: Create CNI directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  become: yes
  with_items:
    - /etc/cni/net.d
    - /opt/cni/bin

- name: Check number of existing CNI plugins
  ansible.builtin.find:
    paths: /opt/cni/bin
    file_type: file
  register: cniplugins_find

- name: Install CNI plugins
  block:
    - name: Download CNI plugins
      ansible.builtin.get_url:
        url: https://github.com/containernetworking/plugins/releases/download/v0.8.6/cni-plugins-linux-amd64-v0.8.6.tgz
        dest: /tmp
    - name: Unpack CNI plugins
      ansible.builtin.unarchive:
        src: /tmp/cni-plugins-linux-amd64-v0.8.6.tgz
        dest: /opt/cni/bin
        remote_src: yes
        owner: root
        group: root
        mode: '0755'
      become: yes
  when: cniplugins_find.files|length == 0

- name: Create bridge network configuration
  block:
    - name: Copy bridge network configuration template
      ansible.builtin.copy:
        src: "{{ role_path }}/files/10-bridge.conf"
        dest: "/etc/cni/net.d/"
    - name: Replace bridge network configuration template - POD_CIDR
      ansible.builtin.lineinfile:
        path: "/etc/cni/net.d/10-bridge.conf"
        regexp: '^(.*)\[\{"subnet":'
        line: '\1[{"subnet": "{{ pod_cidr }}"}]'
        backrefs: yes
  become: yes

- name: Create loopback network configuration
  ansible.builtin.copy:
    src: "{{ role_path }}/files/99-loopback.conf"
    dest: "/etc/cni/net.d/"
  become: yes
