all:
  children:
    k8s-controllers:
      hosts:
        k8s-controller1:
        k8s-controller2:
        k8s-controller3:
    k8s-workers:
      hosts:
        k8s-worker1:
        k8s-worker2:
        k8s-worker3:
