- name: Download kubernetes binary
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/{{ item.item }}"
    dest: /usr/local/bin
  become: yes
- name: Chmod kubernetes binary
  ansible.builtin.file:
    path: "/usr/local/bin/{{ item.item }}"
    state: file
    mode: '0755'
  become: yes